id = "jsasta"
name = "JSasta"
version = "0.1.0"
schema_version = 1
authors = ["JSasta Contributors"]
description = "Language support for JSasta - a JavaScript-like language that compiles to native code"
repository = "https://github.com/nanov/zed-jsasta"

[grammars.jsasta]
repository = "https://github.com/nanov/zed-jsasta"
rev = "6b9851f4ffe9b79af497e8aafe6030c6bcefea2d"
