name = "JSasta"
grammar = "jsasta"
path_suffixes = ["jsa", "js"]
line_comments = ["// ", "/// "]
block_comment = ["/*", "*/"]
autoclose_before = ";:.,=}])"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
    { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
]
